name: "Publish v2 docs"
on:
  push:
    branches:
      - main

env:
  CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN_V2}}

  publish-docs:
    name: Publish v2 docs
    runs-on: ubuntu-latest
    needs: check-changesets
    if: needs.check-changesets.check-changesets.outputs.changesets == 0
    steps:
      - name: setup actions
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.1
          registry-url: https://registry.npmjs.org
      - name: install malta
        working-directory: docs
        run: |
          curl -o malta.tgz -L https://github.com/pilcrowonpaper/malta/releases/latest/download/linux-amd64.tgz
          tar -xvzf malta.tgz
      - name: build
        working-directory: docs
        run: ./linux-amd64/malta build
      - name: install wrangler
        run: npm i -g wrangler
      - name: deploy
        run: wrangler pages deploy docs/dist --project-name arctic --branch main
